build : Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -47,6 +47,18 @@ jobs:
 
       - name: Check tools
         run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
-            cd /root && git pull 2>/dev/null
-          "
+          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
+            echo "...Checking tools on server...";
+            command -v go || echo "go not found!";
+            go version || echo "go version check failed!";
+
+            command -v python3 || echo "python3 not found";
+            python3 --version || echo "python3 version check failed!";
+
+            command -v pyspark || echo "pyspark not found!";
+            pyspark --version || echo "pyspark version check failed!";
+
+            command -v docker || echo "docker not found!";
+            docker --version && cd /root/ && git pull || echo "docker version check failed!";
+          '
+
